import { HugeiconsIcon } from '@hugeicons/react'
import {
  Activity01Icon as H0,
  AlertCircleIcon as H1,
  ArchiveIcon as H2,
  BotIcon as H3,
  BookOpen01Icon,
  BoxesIcon as H4,
  BrainCircuitIcon as H5,
  BrainIcon as H6,
  CableIcon as H7,
  CancelCircleIcon as H8,
  ChatAddIcon as H9,
  ChatIcon as H10,
  CheckCheckIcon as H11,
  CheckIcon as H12,
  ChevronDownIcon as H13,
  ChevronLeftIcon as H14,
  ChevronRightIcon as H15,
  CircleCheckIcon as H16,
  CircleDotIcon as H17,
  CircleIcon as H18,
  ClipboardIcon as H19,
  Clock01Icon,
  CloudDownloadIcon as H20,
  ColumnsThreeCogIcon,
  CopyIcon as H21,
  CornerDownLeftIcon as H22,
  CpuIcon as H23,
  DotIcon as H24,
  ExternalLinkIcon as H25,
  EyeIcon as H26,
  EyeOffIcon as H27,
  FileArchiveIcon as H28,
  FileCodeIcon as H29,
  FileDiffIcon as H30,
  FileEditIcon as H31,
  FileImageIcon as H32,
  FileMinusIcon as H33,
  FilePlusIcon as H34,
  FileSearchIcon as H35,
  FileSpreadsheetIcon as H36,
  FileTypeIcon as H37,
  BulbIcon,
  Cancel01Icon,
  ColorsIcon,
  ComputerIcon,
  Delete01Icon,
  File01Icon,
  FilePenIcon,
  Folder01Icon,
  FolderCodeIcon as H39,
  FolderOpenIcon as H40,
  FolderSearchIcon as H41,
  FolderTreeIcon as H42,
  GitBranchIcon as H43,
  GitBranchPlusIcon as H44,
  GitCommitHorizontalIcon as H45,
  GitForkIcon as H46,
  GlobeIcon as H47,
  GripVerticalIcon as H48,
  HashIcon as H49,
  HelpCircleIcon as H50,
  HistoryIcon as H51,
  InboxIcon as H52,
  Key01Icon as H53,
  KeyboardIcon as H54,
  LayerIcon as H55,
  ListTreeIcon as H56,
  ListXIcon as H57,
  Loading03Icon as H58,
  Maximize01Icon as H59,
  Message01Icon as H60,
  ListViewIcon,
  MailSend01Icon,
  MessageMultiple01Icon as H61,
  Mic01Icon,
  SmartPhone01Icon,
  MinusSignIcon,
  MoonIcon as H62,
  MusicNote01Icon as H63,
  PanelLeftIcon as H64,
  PanelRightIcon as H65,
  PanelRightOpenIcon as H66,
  PencilIcon as H67,
  Plug01Icon,
  PlusSignIcon,
  PlayIcon as H68,
  PuzzleIcon as H69,
  RefreshIcon as H70,
  RotateLeft01Icon,
  ScissorIcon,
  Search01Icon,
  Settings01Icon,
  Shield01Icon,
  SlidersHorizontalIcon as H71,
  SparklesIcon as H72,
  SquareIcon as H73,
  Sun01Icon,
  TableRowsSplitIcon,
  Target01Icon,
  TerminalIcon as H74,
  UndoIcon as H75,
  Upload01Icon,
  UserMultipleIcon,
  Video01Icon,
  Wifi01Icon,
  Wrench01Icon,
  ZapIcon as H76,
} from '@hugeicons/core-free-icons'
import type { IconSvgElement } from '@hugeicons/react'
import type { AppIconComponent, AppIconProps, ThemeIconMap } from '../types'

function hugeGlyph(icon: IconSvgElement): AppIconComponent {
  return function HugeGlyph({ strokeWidth, ...props }: AppIconProps) {
    const opticalStrokeWidth = typeof strokeWidth === 'number' ? strokeWidth : undefined
    return <HugeiconsIcon icon={icon} strokeWidth={opticalStrokeWidth} {...props} />
  }
}

export const hugeiconsIcons = {
  'activity': hugeGlyph(H0),
  'alert-circle': hugeGlyph(H1),
  'alert-triangle': hugeGlyph(H1),
  'archive': hugeGlyph(H2),
  'arrow-down': hugeGlyph(H15),
  'arrow-left': hugeGlyph(H15),
  'arrow-right': hugeGlyph(H15),
  'arrow-up': hugeGlyph(H15),
  'book-open': hugeGlyph(BookOpen01Icon),
  'bot': hugeGlyph(H3),
  'boxes': hugeGlyph(H4),
  'brain': hugeGlyph(H6),
  'brain-circuit': hugeGlyph(H5),
  'cable': hugeGlyph(H7),
  'check': hugeGlyph(H12),
  'check-check': hugeGlyph(H11),
  'check-circle2': hugeGlyph(H16),
  'check-square': hugeGlyph(H12),
  'chevron-down': hugeGlyph(H13),
  'chevron-left': hugeGlyph(H14),
  'chevron-right': hugeGlyph(H15),
  'circle': hugeGlyph(H18),
  'circle-dot': hugeGlyph(H17),
  'clipboard': hugeGlyph(H19),
  'clock': hugeGlyph(Clock01Icon),
  'cloud-download': hugeGlyph(H20),
  'columns2': hugeGlyph(ColumnsThreeCogIcon),
  'copy': hugeGlyph(H21),
  'corner-down-left': hugeGlyph(H22),
  'cpu': hugeGlyph(H23),
  'dot': hugeGlyph(H24),
  'external-link': hugeGlyph(H25),
  'eye': hugeGlyph(H26),
  'eye-off': hugeGlyph(H27),
  'file': hugeGlyph(File01Icon),
  'file-archive': hugeGlyph(H28),
  'file-code': hugeGlyph(H29),
  'file-code2': hugeGlyph(H29),
  'file-diff': hugeGlyph(H30),
  'file-edit': hugeGlyph(H31),
  'file-image': hugeGlyph(H32),
  'file-json': hugeGlyph(H29),
  'file-minus': hugeGlyph(H33),
  'file-plus': hugeGlyph(H34),
  'file-search': hugeGlyph(H35),
  'file-spreadsheet': hugeGlyph(H36),
  'file-text': hugeGlyph(File01Icon),
  'file-type': hugeGlyph(H37),
  'folder': hugeGlyph(Folder01Icon),
  'folder-git2': hugeGlyph(H39),
  'folder-open': hugeGlyph(H40),
  'folder-search': hugeGlyph(H41),
  'folder-tree': hugeGlyph(H42),
  'git-branch': hugeGlyph(H43),
  'git-branch-plus': hugeGlyph(H44),
  'git-commit-horizontal': hugeGlyph(H45),
  'git-fork': hugeGlyph(H46),
  'globe': hugeGlyph(H47),
  'grip-vertical': hugeGlyph(H48),
  'hash': hugeGlyph(H49),
  'history': hugeGlyph(H51),
  'image': hugeGlyph(H32),
  'inbox': hugeGlyph(H52),
  'key-round': hugeGlyph(H53),
  'keyboard': hugeGlyph(H54),
  'layers': hugeGlyph(H55),
  'layout-panel-left': hugeGlyph(H64),
  'lightbulb': hugeGlyph(BulbIcon),
  'list': hugeGlyph(ListViewIcon),
  'list-ordered': hugeGlyph(ListViewIcon),
  'list-tree': hugeGlyph(H56),
  'list-x': hugeGlyph(H57),
  'loader2': hugeGlyph(H58),
  'maximize2': hugeGlyph(H59),
  'message-circle-question': hugeGlyph(H50),
  'message-square': hugeGlyph(H10),
  'message-square-plus': hugeGlyph(H9),
  'message-square-text': hugeGlyph(H60),
  'messages-square': hugeGlyph(H61),
  'mic': hugeGlyph(Mic01Icon),
  'smartphone': hugeGlyph(SmartPhone01Icon),
  'minus': hugeGlyph(MinusSignIcon),
  'monitor': hugeGlyph(ComputerIcon),
  'moon': hugeGlyph(H62),
  'music': hugeGlyph(H63),
  'network': hugeGlyph(Wifi01Icon),
  'palette': hugeGlyph(ColorsIcon),
  'panel-left': hugeGlyph(H64),
  'panel-right': hugeGlyph(H65),
  'panel-right-open': hugeGlyph(H66),
  'pencil': hugeGlyph(H67),
  'pencil-line': hugeGlyph(FilePenIcon),
  'play': hugeGlyph(H68),
  'plug': hugeGlyph(Plug01Icon),
  'plus': hugeGlyph(PlusSignIcon),
  'puzzle': hugeGlyph(H69),
  'refresh-cw': hugeGlyph(H70),
  'rotate-ccw': hugeGlyph(RotateLeft01Icon),
  'rows2': hugeGlyph(TableRowsSplitIcon),
  'scissors': hugeGlyph(ScissorIcon),
  'search': hugeGlyph(Search01Icon),
  'send': hugeGlyph(MailSend01Icon),
  'settings': hugeGlyph(Settings01Icon),
  'shield-check': hugeGlyph(Shield01Icon),
  'sliders-horizontal': hugeGlyph(H71),
  'sparkles': hugeGlyph(H72),
  'square': hugeGlyph(H73),
  'sun': hugeGlyph(Sun01Icon),
  'target': hugeGlyph(Target01Icon),
  'terminal': hugeGlyph(H74),
  'trash2': hugeGlyph(Delete01Icon),
  'undo2': hugeGlyph(H75),
  'upload': hugeGlyph(Upload01Icon),
  'users': hugeGlyph(UserMultipleIcon),
  'video': hugeGlyph(Video01Icon),
  'wrench': hugeGlyph(Wrench01Icon),
  'x': hugeGlyph(Cancel01Icon),
  'x-circle': hugeGlyph(H8),
  'zap': hugeGlyph(H76),
} satisfies ThemeIconMap
