import {
  Activity as I0,
  Archive as I1,
  ArrowDown as I2,
  ArrowDownLeft as I3,
  ArrowLeft as I4,
  ArrowRight as I5,
  ArrowUp as I6,
  Book,
  Brain as I7,
  BrainElectricity,
  CableTag,
  Check as I8,
  CheckCircle as I9,
  CheckSquare as I10,
  Circle as I11,
  Clock as I12,
  ClockRotateRight,
  CloudDownload as I13,
  ColorWheel,
  Copy as I14,
  Cpu as I15,
  DashboardDots,
  Drag,
  Cube as I16,
  Cut as I17,
  Edit as I18,
  Eye as I19,
  EyeClosed,
  Flash as I20,
  Folder as I21,
  GitBranch as I22,
  GitCommit as I23,
  GitFork as I24,
  Globe as I25,
  Group,
  Hashtag,
  HelpCircle as I26,
  Key as I27,
  LayoutLeft as I28,
  LightBulb as I29,
  MediaImage,
  List as I30,
  Maximize as I31,
  Message as I32,
  Laptop,
  Microphone as I33,
  SmartphoneDevice as ISmartphone,
  Minus as I34,
  MusicNote as I35,
  Network as I36,
  OpenBook,
  OpenNewWindow,
  Page as I37,
  PasteClipboard,
  Palette as I38,
  Play as I39,
  Plus as I40,
  Puzzle as I41,
  Refresh as I42,
  RotateCameraLeft,
  Search as I43,
  SidebarCollapse,
  SidebarExpand,
  Spark,
  Send as I44,
  Settings as I45,
  ShieldCheck as I46,
  Square as I47,
  SunLight,
  Table as I48,
  Gps,
  Terminal as I49,
  Trash as I50,
  Undo as I51,
  Upload as I52,
  User,
  VideoCamera,
  WarningCircle as I53,
  WarningTriangle,
  Wifi,
  Wrench as I54,
  X as I55,
} from 'iconoir-react/regular'
import type { ThemeIconMap } from '../types'

export const iconoirIcons = {
  'activity': I0,
  'alert-circle': I53,
  'alert-triangle': WarningTriangle,
  'archive': I1,
  'arrow-down': I2,
  'arrow-left': I4,
  'arrow-right': I5,
  'arrow-up': I6,
  'book-open': OpenBook,
  'bot': I15,
  'boxes': I16,
  'brain': I7,
  'brain-circuit': BrainElectricity,
  'cable': CableTag,
  'check': I8,
  'check-check': I8,
  'check-circle2': I9,
  'check-square': I10,
  'chevron-down': I5,
  'chevron-left': I5,
  'chevron-right': I5,
  'circle': I11,
  'circle-dot': DashboardDots,
  'clipboard': PasteClipboard,
  'clock': I12,
  'cloud-download': I13,
  'columns2': I30,
  'copy': I14,
  'corner-down-left': I3,
  'cpu': I15,
  'dot': DashboardDots,
  'external-link': OpenNewWindow,
  'eye': I19,
  'eye-off': EyeClosed,
  'file': I37,
  'file-archive': I37,
  'file-code': I37,
  'file-code2': I37,
  'file-diff': I37,
  'file-edit': I37,
  'file-image': I37,
  'file-json': I37,
  'file-minus': I37,
  'file-plus': I37,
  'file-search': I37,
  'file-spreadsheet': I48,
  'file-text': I37,
  'file-type': I37,
  'folder': I21,
  'folder-git2': I21,
  'folder-open': I21,
  'folder-search': I21,
  'folder-tree': I21,
  'git-branch': I22,
  'git-branch-plus': I22,
  'git-commit-horizontal': I23,
  'git-fork': I24,
  'globe': I25,
  'grip-vertical': Drag,
  'hash': Hashtag,
  'history': ClockRotateRight,
  'image': MediaImage,
  'inbox': I32,
  'key-round': I27,
  'keyboard': I49,
  'layers': I16,
  'layout-panel-left': I28,
  'lightbulb': I29,
  'list': I30,
  'list-ordered': I30,
  'list-tree': I30,
  'list-x': I30,
  'loader2': I42,
  'maximize2': I31,
  'message-circle-question': I26,
  'message-square': I32,
  'message-square-plus': I32,
  'message-square-text': I32,
  'messages-square': I32,
  'mic': I33,
  'smartphone': ISmartphone,
  'minus': I34,
  'monitor': Laptop,
  'moon': I12,
  'music': I35,
  'network': I36,
  'palette': I38,
  'panel-left': SidebarCollapse,
  'panel-right': SidebarExpand,
  'panel-right-open': SidebarExpand,
  'pencil': I18,
  'pencil-line': I18,
  'play': I39,
  'plug': CableTag,
  'plus': I40,
  'puzzle': I41,
  'refresh-cw': I42,
  'rotate-ccw': RotateCameraLeft,
  'rows2': I30,
  'scissors': I17,
  'search': I43,
  'send': I44,
  'settings': I45,
  'shield-check': I46,
  'sliders-horizontal': I45,
  'sparkles': Spark,
  'square': I47,
  'sun': SunLight,
  'target': Gps,
  'terminal': I49,
  'trash2': I50,
  'undo2': I51,
  'upload': I52,
  'users': Group,
  'video': VideoCamera,
  'wrench': I54,
  'x': I55,
  'x-circle': I55,
  'zap': I20,
} satisfies ThemeIconMap
