import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  BrainCircuit,
  Cable,
  Check,
  CheckCheck,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDot,
  Clipboard,
  Clock,
  CloudDownload,
  Columns2,
  Copy,
  CornerDownLeft,
  Cpu,
  Dot,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode,
  FileCode2,
  FileDiff,
  FileEdit,
  FileImage,
  FileJson,
  FileMinus,
  FilePlus,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileType,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderSearch,
  FolderTree,
  GitBranch,
  GitBranchPlus,
  GitCommitHorizontal,
  GitFork,
  Globe,
  GripVertical,
  Hash,
  History,
  Image,
  Inbox,
  KeyRound,
  Keyboard,
  Layers,
  LayoutPanelLeft,
  Lightbulb,
  List,
  ListOrdered,
  ListTree,
  ListX,
  Loader2,
  Maximize2,
  MessageCircleQuestion,
  MessageSquare,
  MessageSquarePlus,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Smartphone,
  Minus,
  Monitor,
  Moon,
  Music,
  Network,
  Palette,
  PanelLeft,
  PanelRight,
  PanelRightOpen,
  Pencil,
  PencilLine,
  Play,
  Plug,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Rows2,
  Scissors,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Square,
  Sun,
  Target,
  Terminal,
  Trash2,
  Undo2,
  Upload,
  Users,
  Video,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react'
import type { ThemeIconMap } from '../types'

export const lucideIcons = {
  'activity': Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'archive': Archive,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'book-open': BookOpen,
  'bot': Bot,
  'boxes': Boxes,
  'brain': Brain,
  'brain-circuit': BrainCircuit,
  'cable': Cable,
  'check': Check,
  'check-check': CheckCheck,
  'check-circle2': CheckCircle2,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'circle-dot': CircleDot,
  'clipboard': Clipboard,
  'clock': Clock,
  'cloud-download': CloudDownload,
  'columns2': Columns2,
  'copy': Copy,
  'corner-down-left': CornerDownLeft,
  'cpu': Cpu,
  'dot': Dot,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file': File,
  'file-archive': FileArchive,
  'file-code': FileCode,
  'file-code2': FileCode2,
  'file-diff': FileDiff,
  'file-edit': FileEdit,
  'file-image': FileImage,
  'file-json': FileJson,
  'file-minus': FileMinus,
  'file-plus': FilePlus,
  'file-search': FileSearch,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'file-type': FileType,
  'folder': Folder,
  'folder-git2': FolderGit2,
  'folder-open': FolderOpen,
  'folder-search': FolderSearch,
  'folder-tree': FolderTree,
  'git-branch': GitBranch,
  'git-branch-plus': GitBranchPlus,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-fork': GitFork,
  'globe': Globe,
  'grip-vertical': GripVertical,
  'hash': Hash,
  'history': History,
  'image': Image,
  'inbox': Inbox,
  'key-round': KeyRound,
  'keyboard': Keyboard,
  'layers': Layers,
  'layout-panel-left': LayoutPanelLeft,
  'lightbulb': Lightbulb,
  'list': List,
  'list-ordered': ListOrdered,
  'list-tree': ListTree,
  'list-x': ListX,
  'loader2': Loader2,
  'maximize2': Maximize2,
  'message-circle-question': MessageCircleQuestion,
  'message-square': MessageSquare,
  'message-square-plus': MessageSquarePlus,
  'message-square-text': MessageSquareText,
  'messages-square': MessagesSquare,
  'mic': Mic,
  'smartphone': Smartphone,
  'minus': Minus,
  'monitor': Monitor,
  'moon': Moon,
  'music': Music,
  'network': Network,
  'palette': Palette,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  'panel-right-open': PanelRightOpen,
  'pencil': Pencil,
  'pencil-line': PencilLine,
  'play': Play,
  'plug': Plug,
  'plus': Plus,
  'puzzle': Puzzle,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rows2': Rows2,
  'scissors': Scissors,
  'search': Search,
  'send': Send,
  'settings': Settings,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  'sparkles': Sparkles,
  'square': Square,
  'sun': Sun,
  'target': Target,
  'terminal': Terminal,
  'trash2': Trash2,
  'undo2': Undo2,
  'upload': Upload,
  'users': Users,
  'video': Video,
  'wrench': Wrench,
  'x': X,
  'x-circle': XCircle,
  'zap': Zap,
} satisfies ThemeIconMap
