export const APP_ICON_NAMES = [
  'activity',
  'alert-circle',
  'alert-triangle',
  'archive',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'book-open',
  'bot',
  'boxes',
  'brain',
  'brain-circuit',
  'cable',
  'check',
  'check-check',
  'check-circle2',
  'check-square',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'circle',
  'circle-dot',
  'clipboard',
  'clock',
  'cloud-download',
  'columns2',
  'copy',
  'corner-down-left',
  'cpu',
  'dot',
  'external-link',
  'eye',
  'eye-off',
  'file',
  'file-archive',
  'file-code',
  'file-code2',
  'file-diff',
  'file-edit',
  'file-image',
  'file-json',
  'file-minus',
  'file-plus',
  'file-search',
  'file-spreadsheet',
  'file-text',
  'file-type',
  'folder',
  'folder-git2',
  'folder-open',
  'folder-search',
  'folder-tree',
  'git-branch',
  'git-branch-plus',
  'git-commit-horizontal',
  'git-fork',
  'globe',
  'grip-vertical',
  'hash',
  'history',
  'image',
  'inbox',
  'key-round',
  'keyboard',
  'layers',
  'layout-panel-left',
  'lightbulb',
  'list',
  'list-ordered',
  'list-tree',
  'list-x',
  'loader2',
  'maximize2',
  'message-circle-question',
  'message-square',
  'message-square-plus',
  'message-square-text',
  'messages-square',
  'mic',
  'smartphone',
  'minus',
  'monitor',
  'moon',
  'music',
  'network',
  'palette',
  'panel-left',
  'panel-right',
  'panel-right-open',
  'pencil',
  'pencil-line',
  'play',
  'plug',
  'plus',
  'puzzle',
  'refresh-cw',
  'rotate-ccw',
  'rows2',
  'scissors',
  'search',
  'send',
  'settings',
  'shield-check',
  'sliders-horizontal',
  'sparkles',
  'square',
  'sun',
  'target',
  'terminal',
  'trash2',
  'undo2',
  'upload',
  'users',
  'video',
  'wrench',
  'x',
  'x-circle',
  'zap',
] as const

export type AppIconName = (typeof APP_ICON_NAMES)[number]

export const LEGACY_ICON_ALIASES = {
  "Activity": 'activity',
  "AlertCircle": 'alert-circle',
  "AlertTriangle": 'alert-triangle',
  "Archive": 'archive',
  "ArrowDown": 'arrow-down',
  "ArrowLeft": 'arrow-left',
  "ArrowRight": 'arrow-right',
  "ArrowUp": 'arrow-up',
  "BookOpen": 'book-open',
  "Bot": 'bot',
  "Boxes": 'boxes',
  "Brain": 'brain',
  "BrainCircuit": 'brain-circuit',
  "Cable": 'cable',
  "Check": 'check',
  "CheckCheck": 'check-check',
  "CheckCircle2": 'check-circle2',
  "CheckSquare": 'check-square',
  "ChevronDown": 'chevron-down',
  "ChevronLeft": 'chevron-left',
  "ChevronRight": 'chevron-right',
  "Circle": 'circle',
  "CircleDot": 'circle-dot',
  "Clipboard": 'clipboard',
  "Clock": 'clock',
  "CloudDownload": 'cloud-download',
  "Columns2": 'columns2',
  "Copy": 'copy',
  "CornerDownLeft": 'corner-down-left',
  "Cpu": 'cpu',
  "Dot": 'dot',
  "ExternalLink": 'external-link',
  "Eye": 'eye',
  "EyeOff": 'eye-off',
  "File": 'file',
  "FileArchive": 'file-archive',
  "FileCode": 'file-code',
  "FileCode2": 'file-code2',
  "FileDiff": 'file-diff',
  "FileEdit": 'file-edit',
  "FileImage": 'file-image',
  "FileJson": 'file-json',
  "FileMinus": 'file-minus',
  "FilePlus": 'file-plus',
  "FileSearch": 'file-search',
  "FileSpreadsheet": 'file-spreadsheet',
  "FileText": 'file-text',
  "FileType": 'file-type',
  "Folder": 'folder',
  "FolderGit2": 'folder-git2',
  "FolderOpen": 'folder-open',
  "FolderSearch": 'folder-search',
  "FolderTree": 'folder-tree',
  "GitBranch": 'git-branch',
  "GitBranchPlus": 'git-branch-plus',
  "GitCommitHorizontal": 'git-commit-horizontal',
  "GitFork": 'git-fork',
  "Globe": 'globe',
  "GripVertical": 'grip-vertical',
  "Hash": 'hash',
  "History": 'history',
  "Image": 'image',
  "Inbox": 'inbox',
  "KeyRound": 'key-round',
  "Keyboard": 'keyboard',
  "Layers": 'layers',
  "LayoutPanelLeft": 'layout-panel-left',
  "Lightbulb": 'lightbulb',
  "List": 'list',
  "ListOrdered": 'list-ordered',
  "ListTree": 'list-tree',
  "ListX": 'list-x',
  "Loader2": 'loader2',
  "Maximize2": 'maximize2',
  "MessageCircleQuestion": 'message-circle-question',
  "MessageSquare": 'message-square',
  "MessageSquarePlus": 'message-square-plus',
  "MessageSquareText": 'message-square-text',
  "MessagesSquare": 'messages-square',
  "Mic": 'mic',
  "Smartphone": 'smartphone',
  "Minus": 'minus',
  "Monitor": 'monitor',
  "Moon": 'moon',
  "Music": 'music',
  "Network": 'network',
  "Palette": 'palette',
  "PanelLeft": 'panel-left',
  "PanelRight": 'panel-right',
  "PanelRightOpen": 'panel-right-open',
  "Pencil": 'pencil',
  "PencilLine": 'pencil-line',
  "Play": 'play',
  "Plug": 'plug',
  "Plus": 'plus',
  "Puzzle": 'puzzle',
  "RefreshCw": 'refresh-cw',
  "RotateCcw": 'rotate-ccw',
  "Rows2": 'rows2',
  "Scissors": 'scissors',
  "Search": 'search',
  "Send": 'send',
  "Settings": 'settings',
  "ShieldCheck": 'shield-check',
  "SlidersHorizontal": 'sliders-horizontal',
  "Sparkles": 'sparkles',
  "Square": 'square',
  "Sun": 'sun',
  "Target": 'target',
  "Terminal": 'terminal',
  "Trash2": 'trash2',
  "Undo2": 'undo2',
  "Upload": 'upload',
  "Users": 'users',
  "Video": 'video',
  "Wrench": 'wrench',
  "X": 'x',
  "XCircle": 'x-circle',
  "Zap": 'zap',
} as const satisfies Record<string, AppIconName>

const normalizedLegacyNames = new Map(
  Object.entries(LEGACY_ICON_ALIASES).map(([name, semantic]) => [name.toLowerCase(), semantic]),
)

export function normalizeLegacyIconName(value: unknown): AppIconName | undefined {
  if (typeof value !== 'string') return undefined
  return normalizedLegacyNames.get(value.trim().toLowerCase())
}
